#!/bin/bash

conda=conda
ENV_NAME=Bioiso
$conda create -n $ENV_NAME python=3.9.11
$conda activate $ENV_NAME

$conda install scipy numpy pandas scikit-learn
pip install matplotlib
$conda install -c conda-forge rdkit=2022.03.1
$conda install seaborn

# 1. cudatoolkit = 11.3
$conda install pytorch==1.11.0 cudatoolkit=11.3 -c pytorch
pip install torch-scatter==2.0.9 torch-sparse==0.6.15 torch-cluster==1.6.0 torch-geometric==2.1.0 -f https://data.pyg.org/whl/torch-1.11.0+cu113.html
